<a href="https://colab.research.google.com/github/celeneheng/IS170_Binder/blob/4-Association-Rules/HW5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#set up the libraries
# we use apriori for SUPPORT and association_rules for CONFIDENCE, LIFT and CONVICTION
import numpy as np
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder

In [ ]:
#Loading the dataset
from google.colab import files
uploaded = files.upload()

Saving AUTOZONEDataSet.csv to AUTOZONEDataSet.csv

In [ ]:
#Since it's missing a column header, so we create new column header name
df=pd.read_csv('AUTOZONEDataSet.csv', names=['autoparts'], sep=',')
df.head()

                               autoparts
0                 OIL,COOLANT,CAR SCENTS
1  COOLANT,OIL,CAR SCENTS,PRESSURE GAUGE
2                COOLANT,WIPER FLUID,GUM
3               GUM,CAR SOAP,COOLANT,OIL
4        CAR SOAP,WIPER FLUID,CAR SCENTS

In [ ]:
#data size
df.shape

(20, 1)

In [ ]:
#the following code converts a pandas dataframe into a list of lists.
data=list(df["autoparts"].apply(lambda x:x.split(",")))
data

[['OIL', 'COOLANT', 'CAR SCENTS'],
 ['COOLANT', 'OIL', 'CAR SCENTS', 'PRESSURE GAUGE'],
 ['COOLANT', 'WIPER FLUID', 'GUM'],
 ['GUM', 'CAR SOAP', 'COOLANT', 'OIL'],
 ['CAR SOAP', 'WIPER FLUID', 'CAR SCENTS'],
 ['COOLANT', 'WIPER FLUID', 'FUNNEL'],
 ['CAR SOAP', 'WIPER FLUID', 'PRESSURE GAUGE'],
 ['CAR SOAP', 'COOLANT', 'WIPER FLUID', 'CAR SCENTS'],
 ['GUM', 'CAR SOAP', 'COOLANT', 'WIPER FLUID'],
 ['COOLANT', 'OIL'],
 ['OIL FILTERS', '', 'CAR SCENTS', 'PRESSURE GAUGE'],
 ['OIL FILTERS', 'CAR SCENTS', 'PRESSURE GAUGE'],
 ['OIL FILTERS', 'GLOVES'],
 ['COOLANT', 'OIL FILTERS', ''],
 ['COOLANT', 'GLOVES', 'CAR SCENTS'],
 ['OIL FILTERS', 'GLOVES', 'PRESSURE GAUGE'],
 ['COOLANT', 'GLOVES', 'FUNNEL'],
 ['COOLANT', 'OIL FILTERS', 'GLOVES'],
 ['COOLANT', 'OIL FILTERS', 'GLOVES'],
 ['WIPER FLUID', 'OIL', 'OIL FILTERS', 'PRESSURE GAUGE']]

In [ ]:
#Let's transform the list with one-hot encoding
a=TransactionEncoder()
a_data=a.fit(data).transform(data)
df=pd.DataFrame(a_data, columns=a.columns_)
df=df.replace(True,1)
df=df.replace(False,0)
df

,,CAR SCENTS,CAR SOAP,COOLANT,FUNNEL,GLOVES,GUM,OIL,OIL FILTERS,PRESSURE GAUGE,WIPER FLUID
0,0,1,0,1,0,0,0,1,0,0,0
1,0,1,0,1,0,0,0,1,0,1,0
2,0,0,0,1,0,0,1,0,0,0,1
3,0,0,1,1,0,0,1,1,0,0,0
4,0,1,1,0,0,0,0,0,0,0,1
5,0,0,0,1,1,0,0,0,0,0,1
6,0,0,1,0,0,0,0,0,0,1,1
7,0,1,1,1,0,0,0,0,0,0,1
8,0,0,1,1,0,0,1,0,0,0,1
9,0,0,0,1,0,0,0,1,0,0,0
10,1,1,0,0,0,0,0,0,1,1,0
11,0,1,0,0,0,0,0,0,1,1,0
12,0,0,0,0,0,1,0,0,1,0,0
13,1,0,0,1,0,0,0,0,1,0,0
14,0,1,0,1,0,1,0,0,0,0,0
15,0,0,0,0,0,1,0,0,1,1,0
16,0,0,0,1,1,1,0,0,0,0,0
17,0,0,0,1,0,1,0,0,1,0,0
18,0,0,0,1,0,1,0,0,1,0,0
19,0,0,0,0,0,0,0,1,1,1,1

In [ ]:
#Set a threshold value for the support value and calculate the support value
df=apriori(df,min_support=0.2, use_colnames=True)
df

    support                       itemsets
0      0.35                   (CAR SCENTS)
1      0.25                     (CAR SOAP)
2      0.65                      (COOLANT)
3      0.30                       (GLOVES)
4      0.25                          (OIL)
5      0.40                  (OIL FILTERS)
6      0.30               (PRESSURE GAUGE)
7      0.35                  (WIPER FLUID)
8      0.20          (CAR SCENTS, COOLANT)
9      0.20        (WIPER FLUID, CAR SOAP)
10     0.20              (GLOVES, COOLANT)
11     0.20                 (COOLANT, OIL)
12     0.20         (WIPER FLUID, COOLANT)
13     0.20          (OIL FILTERS, GLOVES)
14     0.20  (PRESSURE GAUGE, OIL FILTERS)

Support is used to show the frequency of how many times the items was purchased out of all the purchases

In [ ]:
#Here is the CONFIDENCE (Try different min_threshold value to explore this more)
df_ar=association_rules(df,metric="confidence", min_threshold=0.3)
df_ar

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(CAR SCENTS),(COOLANT),0.35,0.65,0.2,0.571429,0.879121,-0.0275,0.816667
1,(COOLANT),(CAR SCENTS),0.65,0.35,0.2,0.307692,0.879121,-0.0275,0.938889
2,(WIPER FLUID),(CAR SOAP),0.35,0.25,0.2,0.571429,2.285714,0.1125,1.750000
3,(CAR SOAP),(WIPER FLUID),0.25,0.35,0.2,0.800000,2.285714,0.1125,3.250000
4,(GLOVES),(COOLANT),0.30,0.65,0.2,0.666667,1.025641,0.0050,1.050000
5,(COOLANT),(GLOVES),0.65,0.30,0.2,0.307692,1.025641,0.0050,1.011111
6,(COOLANT),(OIL),0.65,0.25,0.2,0.307692,1.230769,0.0375,1.083333
7,(OIL),(COOLANT),0.25,0.65,0.2,0.800000,1.230769,0.0375,1.750000
8,(WIPER FLUID),(COOLANT),0.35,0.65,0.2,0.571429,0.879121,-0.0275,0.816667
9,(COOLANT),(WIPER FLUID),0.65,0.35,0.2,0.307692,0.879121,-0.0275,0.938889
10,(OIL FILTERS),(GLOVES),0.40,0.30,0.2,0.500000,1.666667,0.0800,1.400000
11,(GLOVES),(OIL FILTERS),0.30,0.40,0.2,0.666667,1.666667,0.0800,1.800000
12,(PRESSURE GAUGE),(OIL FILTERS),0.30,0.40,0.2,0.666667,1.666667,0.0800,1.800000
13,(OIL FILTERS),(PRESSURE GAUGE),0.40,0.30,0.2,0.500000,1.666667,0.0800,1.400000

The first and second rows (Coolant -> Car Scents) show CONFIDENCE .57 and .31 which add up to .89 which means the two items are bought togetehr 89%. The third row (wiper pluid -> car soap show 0.57 which means the two items are bought together only 35% (or when wiper fluid is bought only 57% chance car soap is also bought).

confidence shows the probablity of and antecedent and consequent occuring together.

In [ ]:
#Here is LIFT (try different min_threshold value to explore more) 
df_ar=association_rules(df,metric="lift", min_threshold=0.8)
df_ar

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(CAR SCENTS),(COOLANT),0.35,0.65,0.2,0.571429,0.879121,-0.0275,0.816667
1,(COOLANT),(CAR SCENTS),0.65,0.35,0.2,0.307692,0.879121,-0.0275,0.938889
2,(WIPER FLUID),(CAR SOAP),0.35,0.25,0.2,0.571429,2.285714,0.1125,1.750000
3,(CAR SOAP),(WIPER FLUID),0.25,0.35,0.2,0.800000,2.285714,0.1125,3.250000
4,(GLOVES),(COOLANT),0.30,0.65,0.2,0.666667,1.025641,0.0050,1.050000
5,(COOLANT),(GLOVES),0.65,0.30,0.2,0.307692,1.025641,0.0050,1.011111
6,(COOLANT),(OIL),0.65,0.25,0.2,0.307692,1.230769,0.0375,1.083333
7,(OIL),(COOLANT),0.25,0.65,0.2,0.800000,1.230769,0.0375,1.750000
8,(WIPER FLUID),(COOLANT),0.35,0.65,0.2,0.571429,0.879121,-0.0275,0.816667
9,(COOLANT),(WIPER FLUID),0.65,0.35,0.2,0.307692,0.879121,-0.0275,0.938889
10,(OIL FILTERS),(GLOVES),0.40,0.30,0.2,0.500000,1.666667,0.0800,1.400000
11,(GLOVES),(OIL FILTERS),0.30,0.40,0.2,0.666667,1.666667,0.0800,1.800000
12,(PRESSURE GAUGE),(OIL FILTERS),0.30,0.40,0.2,0.666667,1.666667,0.0800,1.800000
13,(OIL FILTERS),(PRESSURE GAUGE),0.40,0.30,0.2,0.500000,1.666667,0.0800,1.400000

The two rows (Coolant & car scents) show LIFT 1.8 which is a positive correlation between the two. The rows 2 and 3 (Wiper fluid -> car soap show LIFT 4.5 which is high positive correlation between the two. 

Lift is about the correlation between the antecedant and consquent

In [ ]:
#Let's view our interpretation values using the Association rule function
df_ar=association_rules(df,metric="conviction", min_threshold=0.8)
df_ar

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(CAR SCENTS),(COOLANT),0.35,0.65,0.2,0.571429,0.879121,-0.0275,0.816667
1,(COOLANT),(CAR SCENTS),0.65,0.35,0.2,0.307692,0.879121,-0.0275,0.938889
2,(WIPER FLUID),(CAR SOAP),0.35,0.25,0.2,0.571429,2.285714,0.1125,1.750000
3,(CAR SOAP),(WIPER FLUID),0.25,0.35,0.2,0.800000,2.285714,0.1125,3.250000
4,(GLOVES),(COOLANT),0.30,0.65,0.2,0.666667,1.025641,0.0050,1.050000
5,(COOLANT),(GLOVES),0.65,0.30,0.2,0.307692,1.025641,0.0050,1.011111
6,(COOLANT),(OIL),0.65,0.25,0.2,0.307692,1.230769,0.0375,1.083333
7,(OIL),(COOLANT),0.25,0.65,0.2,0.800000,1.230769,0.0375,1.750000
8,(WIPER FLUID),(COOLANT),0.35,0.65,0.2,0.571429,0.879121,-0.0275,0.816667
9,(COOLANT),(WIPER FLUID),0.65,0.35,0.2,0.307692,0.879121,-0.0275,0.938889
10,(OIL FILTERS),(GLOVES),0.40,0.30,0.2,0.500000,1.666667,0.0800,1.400000
11,(GLOVES),(OIL FILTERS),0.30,0.40,0.2,0.666667,1.666667,0.0800,1.800000
12,(PRESSURE GAUGE),(OIL FILTERS),0.30,0.40,0.2,0.666667,1.666667,0.0800,1.800000
13,(OIL FILTERS),(PRESSURE GAUGE),0.40,0.30,0.2,0.500000,1.666667,0.0800,1.400000

CONVICTION is same as LIFT except CONVICTION also gives the directed measure. Meaning it gives the correlation when they are purchased seperately. If you look at all the rows the convictions are close to 1 none of them are infinity therfore there are no correlations in this data set.

# **Hey boss looking at the data the most sold item was coolant and the least sold item was oil. Coolant was sold in about 65% of the transcations and oil was sold in about 25% of the transactions. Car soap->wiper fluid had the highest confidence those two items have a higher probablity of being purchased than anything else. with a confidence of 1.3. However after calculating the lift and conviction there is no indication of a correlation between any of the items.**

In [ ]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules  #we need apriori for SUPPORT and association_rules for CONFIDENCE, LIFT, CONVICTION

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving fastfood_dataset.csv to fastfood_dataset (1).csv

In [ ]:
#Since it's missing a header we'll create one, the new column header 'Products' 
df=pd.read_csv('fastfood_dataset.csv', names=['fast_food'])
df.head()

                                           fast_food
0  Hamburger, Hotdog, Ice Cream, Chili Bean Fries...
1  Ketchup, Hotdog, Ice Cream,Chili Fries, French...
2          Hamburger, Apple, Chili Fries, French Fry
3               Hamburger, Ketchup, French Fry, Soda
4     Hamburger, Hotdog, Soda, Ice cream, French Fry

In [ ]:
df.shape

(5, 12)

In [ ]:
#the following code converts a pandas dataframe into a list of lists.
data=list(df["fast_food"].apply(lambda x:x.split(",")))
data

[['Hamburger',
  ' Hotdog',
  ' Ice Cream',
  ' Chili Bean Fries',
  ' French Fry',
  ' Soda'],
 ['Ketchup', ' Hotdog', ' Ice Cream', 'Chili Fries', ' French Fry', ' Soda'],
 ['Hamburger', ' Apple', ' Chili Fries', ' French Fry'],
 ['Hamburger', ' Ketchup', ' French Fry', ' Soda'],
 ['Hamburger', ' Hotdog', ' Soda', ' Ice cream', ' French Fry']]

In [ ]:
#Let's transform the list with one-hot encoding (make sure you understand the one-hot encoding concept first)
#Each column represents an item and each row represent a record or a transaction. 
#Initially, if that particular item occurs then it's labeled TRUE, if not then FALSE.
#After that, TRUE is converted to 1 and FALSE to 0 because computer loves numeric values.

from mlxtend.preprocessing import TransactionEncoder
a=TransactionEncoder()
a_data=a.fit(data).transform(data)
df=pd.DataFrame(a_data, columns=a.columns_)

#Turn False & True to 0 & 1 for easy readability
df=df.replace(False,0)
df=df.replace(True,1)

df

,Apple,Chili Bean Fries,Chili Fries,French Fry,Hotdog,Ice Cream,Ice cream,Ketchup,Soda,Chili Fries,Hamburger,Ketchup
0,0,1,0,1,1,1,0,0,1,0,1,0
1,0,0,0,1,1,1,0,0,1,1,0,1
2,1,0,1,1,0,0,0,0,0,0,1,0
3,0,0,0,1,0,0,0,1,1,0,1,0
4,0,0,0,1,1,0,1,0,1,0,1,0

In [ ]:
#We'll try 0.2 for the SUPPORT threshold value (but you can set it to any value you want).
# The parameter (use_colnames=True) is used to convert the integer back to its respective name.
# apriori is only used with SUPPORT not the others.

df=apriori(df,min_support=0.2,use_colnames=True)
df

     support                                           itemsets
0        0.2                                           ( Apple)
1        0.2                                ( Chili Bean Fries)
2        0.2                                     ( Chili Fries)
3        1.0                                      ( French Fry)
4        0.6                                          ( Hotdog)
..       ...                                                ...
142      0.2  (Chili Fries,  Hotdog,  Soda,  French Fry, Ket...
143      0.2  (Chili Fries,  Ice Cream,  Soda,  French Fry, ...
144      0.2  (Chili Fries,  Ice Cream,  Hotdog,  Soda, Ketc...
145      0.2  ( Ice Cream,  Hotdog,  Chili Bean Fries,  Soda...
146      0.2  (Chili Fries,  Ice Cream,  Hotdog,  Soda,  Fre...

[147 rows x 2 columns]

With the SUPPORT values above, you can try and match your own manual calculation. You notice how some are grouped with two. Not only single item, but also group of two or more are tested. Any item or group of items didn't make 0.2 then they are not listed. French fries were sold 100% of the time with every transaction. Hotdogs were also regularly sold about 60% of the transactions.

In [ ]:
#For the CONFIDENCE parameter, we use the 'association_rules' function below.
df_ar=association_rules(df,metric="confidence", min_threshold=0.6)
df_ar

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,( Chili Fries),( Apple),0.2,0.2,0.2,1.0,5.00,0.16,inf
1,( Apple),( Chili Fries),0.2,0.2,0.2,1.0,5.00,0.16,inf
2,( Apple),( French Fry),0.2,1.0,0.2,1.0,1.00,0.00,inf
3,( Apple),(Hamburger),0.2,0.8,0.2,1.0,1.25,0.04,inf
4,( Chili Bean Fries),( French Fry),0.2,1.0,0.2,1.0,1.00,0.00,inf
...,...,...,...,...,...,...,...,...,...
793,"( Hotdog, Ketchup)","( Ice Cream, Soda, Chili Fries, French Fry)",0.2,0.2,0.2,1.0,5.00,0.16,inf
794,"( Soda, Ketchup)","( Ice Cream, French Fry, Chili Fries, Hotdog)",0.2,0.2,0.2,1.0,5.00,0.16,inf
795,"(Ketchup, French Fry)","( Ice Cream, Soda, Chili Fries, Hotdog)",0.2,0.2,0.2,1.0,5.00,0.16,inf
796,(Chili Fries),"( Ice Cream, Hotdog, Soda, French Fry, Ketc...",0.2,0.2,0.2,1.0,5.00,0.16,inf
797,(Ketchup),"(Chili Fries, Ice Cream, Hotdog, Soda, Fre...",0.2,0.2,0.2,1.0,5.00,0.16,inf

From above result, shows that all the rows have a confidence of 1 meaning that the pairing occur 100% of the time together.

In [ ]:
#Here is the LIFT parameter.
df_ar=association_rules(df,metric="lift", min_threshold=1)
df_ar

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,( Chili Fries),( Apple),0.2,0.2,0.2,1.000000,5.000000,0.16,inf
1,( Apple),( Chili Fries),0.2,0.2,0.2,1.000000,5.000000,0.16,inf
2,( Apple),( French Fry),0.2,1.0,0.2,1.000000,1.000000,0.00,inf
3,( French Fry),( Apple),1.0,0.2,0.2,0.200000,1.000000,0.00,1.000000
4,(Hamburger),( Apple),0.8,0.2,0.2,0.250000,1.250000,0.04,1.066667
...,...,...,...,...,...,...,...,...,...
1311,( Ice Cream),"(Chili Fries, Hotdog, Soda, French Fry, Ket...",0.4,0.2,0.2,0.500000,2.500000,0.12,1.600000
1312,( Hotdog),"(Chili Fries, Ice Cream, Soda, French Fry, ...",0.6,0.2,0.2,0.333333,1.666667,0.08,1.200000
1313,( Soda),"(Chili Fries, Ice Cream, Hotdog, French Fry...",0.8,0.2,0.2,0.250000,1.250000,0.04,1.066667
1314,( French Fry),"(Chili Fries, Ice Cream, Hotdog, Soda, Ketc...",1.0,0.2,0.2,0.200000,1.000000,0.00,1.000000
1315,(Ketchup),"(Chili Fries, Ice Cream, Hotdog, Soda, Fre...",0.2,0.2,0.2,1.000000,5.000000,0.16,inf

From above result, the LIFT  tells us there is not a correlation when apples and french fries are purchased. There was a slight positve correlation between apples and french fries. There was a high positive correlation between apples and chili fries.

In [ ]:
#Here is the CONVICTION parameter. 
df_ar=association_rules(df,metric="conviction", min_threshold=1.0)
df_ar

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,( Chili Fries),( Apple),0.2,0.2,0.2,1.000000,5.000000,0.16,inf
1,( Apple),( Chili Fries),0.2,0.2,0.2,1.000000,5.000000,0.16,inf
2,( Apple),( French Fry),0.2,1.0,0.2,1.000000,1.000000,0.00,inf
3,( French Fry),( Apple),1.0,0.2,0.2,0.200000,1.000000,0.00,1.000000
4,(Hamburger),( Apple),0.8,0.2,0.2,0.250000,1.250000,0.04,1.066667
...,...,...,...,...,...,...,...,...,...
1311,( Ice Cream),"(Chili Fries, Hotdog, Soda, French Fry, Ket...",0.4,0.2,0.2,0.500000,2.500000,0.12,1.600000
1312,( Hotdog),"(Chili Fries, Ice Cream, Soda, French Fry, ...",0.6,0.2,0.2,0.333333,1.666667,0.08,1.200000
1313,( Soda),"(Chili Fries, Ice Cream, Hotdog, French Fry...",0.8,0.2,0.2,0.250000,1.250000,0.04,1.066667
1314,( French Fry),"(Chili Fries, Ice Cream, Hotdog, Soda, Ketc...",1.0,0.2,0.2,0.200000,1.000000,0.00,1.000000
1315,(Ketchup),"(Chili Fries, Ice Cream, Hotdog, Soda, Fre...",0.2,0.2,0.2,1.000000,5.000000,0.16,inf

From above result, the CONVICTION tells us that there is positive correlation between apples and french fries and apples and chili fries.
all other rows did not show a correlation.

# Hey boss after analyzing the data set French fries were sold 100% of the time! Every transaction had a sale of French Fries. Our second best seller was Hotdogs we sold a hotdog in about 60% of the all transactions. 
# We paired French fries and Apples, Chili Fries and Apples, and Hamburger and Apples the results, shows that all have a confidence of 1 meaning that the pairing occur 100% of the time together.Also, hotdogs and apples were never sold in the same transaction.


# LIFT  tells us there is not a correlation when apples and french fries are purchased. There was a slight positve correlation between apples and french fries. There was a high positive correlation between apples and chili fries. From the CONVICTION tells us that there is positive correlation between apples and french fries; and apples and chili fries. All the other rows did not show a correlation. **bold text**