<a href="https://colab.research.google.com/github/celeneheng/IS170_Binder/blob/1-Feature-Engineeering/Lab2Part3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving freshman_kgss.csv to freshman_kgss.csv

In [ ]:
pandas.read_csv('freshman_kgss.csv')

   Sex  Weight(Sep)   Weight(Apr)  BMI(Sep)  BMI(Apr)
0    M         72.0          59.0     22.02     18.14
1    M         97.0          86.0     19.70     17.44
2    M         74.0          69.0     24.09     22.43
3    M         93.0          88.0     26.97     25.57
4    F         68.0          64.0     21.51     20.10
..  ..          ...           ...       ...       ...
62   M         65.0          71.0     22.51     24.45
63   M         75.0          82.0     23.69     25.80
64   F         42.0          49.0     15.08     17.74
65   M         74.0          82.0     22.64     25.33
66   M         94.0         105.0     36.57     40.86

[67 rows x 5 columns]

In [ ]:
df = pandas.read_csv('freshman_kgss.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sex           67 non-null     object
 1   Weight(Sep)   67 non-null     float64
 2    Weight(Apr)  67 non-null     float64
 3   BMI(Sep)      67 non-null     float64
 4   BMI(Apr)      67 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.7+ KB

In [ ]:
df.dropna(how='all')
df

   Sex  Weight(Sep)   Weight(Apr)  BMI(Sep)  BMI(Apr)
0    M         72.0          59.0     22.02     18.14
1    M         97.0          86.0     19.70     17.44
2    M         74.0          69.0     24.09     22.43
3    M         93.0          88.0     26.97     25.57
4    F         68.0          64.0     21.51     20.10
..  ..          ...           ...       ...       ...
62   M         65.0          71.0     22.51     24.45
63   M         75.0          82.0     23.69     25.80
64   F         42.0          49.0     15.08     17.74
65   M         74.0          82.0     22.64     25.33
66   M         94.0         105.0     36.57     40.86

[67 rows x 5 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder( )

label = le.fit_transform(df['Sex'])

label

array([1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1])

In [ ]:
df.drop("Sex", axis= 1, inplace=True)

df["Sex"] = label

df

    Weight(Sep)   Weight(Apr)  BMI(Sep)  BMI(Apr)  Sex
0          72.0          59.0     22.02     18.14    1
1          97.0          86.0     19.70     17.44    1
2          74.0          69.0     24.09     22.43    1
3          93.0          88.0     26.97     25.57    1
4          68.0          64.0     21.51     20.10    0
..          ...           ...       ...       ...  ...
62         65.0          71.0     22.51     24.45    1
63         75.0          82.0     23.69     25.80    1
64         42.0          49.0     15.08     17.74    0
65         74.0          82.0     22.64     25.33    1
66         94.0         105.0     36.57     40.86    1

[67 rows x 5 columns]

In [ ]:
old_cols=df.columns.values
new_cols=['Weight(Sep)','BMI(Sep)','Sex']
df=df.reindex(columns=new_cols)
df

    Weight(Sep)  BMI(Sep)  Sex
0          72.0     22.02    1
1          97.0     19.70    1
2          74.0     24.09    1
3          93.0     26.97    1
4          68.0     21.51    0
..          ...       ...  ...
62         65.0     22.51    1
63         75.0     23.69    1
64         42.0     15.08    0
65         74.0     22.64    1
66         94.0     36.57    1

[67 rows x 3 columns]

In [ ]:
print(df.rename(columns={'Weight(Sep)':'Sep','BMI(Sep)':'Sep Fat'}))

     Sep  Sep Fat  Sex
0   72.0    22.02    1
1   97.0    19.70    1
2   74.0    24.09    1
3   93.0    26.97    1
4   68.0    21.51    0
..   ...      ...  ...
62  65.0    22.51    1
63  75.0    23.69    1
64  42.0    15.08    0
65  74.0    22.64    1
66  94.0    36.57    1

[67 rows x 3 columns]