<a href="https://colab.research.google.com/github/celeneheng/IS170_Binder/blob/1-Feature-Engineeering/Lab2Part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving healthcare_data-2.csv to healthcare_data-2.csv

In [ ]:
pandas.read_csv('healthcare_data-2.csv')

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,severe
1,1,85,66,29,0,26.6,0.351,31,min
2,8,183,64,0,0,23.3,0.672,32,moderate
3,1,89,66,23,94,28.1,0.167,21,min
4,0,137,40,35,168,43.1,2.288,33,severe
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,min
764,2,122,70,27,0,36.8,0.340,27,moderate
765,5,121,72,23,112,26.2,0.245,30,severe
766,1,126,60,0,0,30.1,0.349,47,mild
767,1,93,70,31,0,30.4,0.315,23,min

In [ ]:
df = pandas.read_csv('healthcare_data-2.csv')

In [ ]:
df.info() #information about a DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    object
dtypes: float64(2), int64(6), object(1)
memory usage: 54.1+ KB

In [ ]:
df.dropna(how='all') #removed any row with a missing value
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,3
1,1,85,66,29,0,26.6,0.351,31,1
2,8,183,64,0,0,23.3,0.672,32,2
3,1,89,66,23,94,28.1,0.167,21,1
4,0,137,40,35,168,43.1,2.288,33,3
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,1
764,2,122,70,27,0,36.8,0.340,27,2
765,5,121,72,23,112,26.2,0.245,30,3
766,1,126,60,0,0,30.1,0.349,47,0
767,1,93,70,31,0,30.4,0.315,23,1

In [ ]:
df[['Insulin','SkinThickness']]=df[['Insulin','SkinThickness']].fillna(value=df[['Insulin','SkinThickness']].mean())
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,3
1,1,85,66,29,0,26.6,0.351,31,1
2,8,183,64,0,0,23.3,0.672,32,2
3,1,89,66,23,94,28.1,0.167,21,1
4,0,137,40,35,168,43.1,2.288,33,3
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,1
764,2,122,70,27,0,36.8,0.340,27,2
765,5,121,72,23,112,26.2,0.245,30,3
766,1,126,60,0,0,30.1,0.349,47,0
767,1,93,70,31,0,30.4,0.315,23,1

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder( )

label = le.fit_transform(df['Outcome'])

label

array([3, 1, 2, 1, 3, 0, 0, 0, 3, 0, 0, 3, 1, 1, 2, 0, 2, 0, 0, 0, 3, 1,
       3, 0, 2, 2, 0, 3, 3, 0, 3, 2, 3, 1, 0, 3, 3, 0, 1, 2, 1, 3, 2, 2,
       2, 2, 3, 1, 3, 1, 2, 2, 2, 0, 0, 1, 1, 0, 0, 0, 1, 1, 2, 1, 3, 3,
       2, 1, 3, 0, 1, 0, 3, 0, 0, 2, 1, 3, 0, 0, 0, 1, 1, 2, 1, 3, 1, 3,
       2, 1, 1, 1, 0, 0, 3, 0, 1, 3, 2, 3, 1, 1, 3, 3, 0, 1, 2, 3, 1, 2,
       0, 2, 0, 3, 2, 3, 2, 3, 3, 2, 2, 3, 2, 2, 1, 3, 0, 3, 0, 2, 1, 2,
       2, 3, 2, 0, 2, 3, 2, 3, 2, 3, 2, 0, 0, 0, 0, 3, 1, 0, 0, 1, 2, 3,
       1, 3, 3, 2, 2, 0, 1, 0, 1, 1, 2, 1, 2, 2, 3, 1, 1, 2, 1, 2, 3, 3,
       1, 0, 3, 3, 3, 3, 2, 1, 3, 2, 3, 1, 2, 3, 1, 3, 0, 1, 1, 1, 0, 0,
       3, 3, 3, 0, 0, 1, 2, 1, 3, 1, 2, 3, 1, 0, 3, 2, 3, 0, 1, 0, 0, 3,
       1, 0, 0, 1, 2, 3, 1, 2, 0, 1, 2, 2, 3, 1, 0, 0, 0, 1, 2, 3, 3, 0,
       3, 3, 0, 0, 0, 2, 0, 3, 2, 0, 3, 3, 3, 1, 2, 0, 0, 2, 2, 3, 3, 2,
       3, 1, 3, 1, 1, 3, 2, 0, 2, 2, 2, 1, 3, 3, 2, 3, 1, 3, 3, 3, 3, 0,
       1, 2, 1, 0, 1, 2, 0, 0, 1, 0, 3, 2, 1, 1, 2, 3, 1, 1, 1, 2, 2, 3,
       2, 2, 1, 0, 1, 2, 2, 3, 2, 3, 0, 1, 0, 3, 0, 3, 3, 2, 2, 3, 2, 1,
       3, 3, 1, 0, 3, 1, 1, 3, 1, 1, 0, 3, 2, 0, 0, 2, 1, 0, 0, 3, 3, 3,
       1, 1, 2, 0, 2, 0, 0, 1, 2, 2, 3, 1, 1, 0, 3, 3, 2, 3, 0, 2, 2, 3,
       1, 2, 3, 1, 0, 1, 2, 1, 1, 3, 2, 2, 2, 2, 0, 0, 1, 0, 0, 0, 2, 0,
       3, 2, 0, 0, 2, 0, 1, 2, 1, 3, 0, 3, 3, 0, 2, 0, 3, 2, 0, 2, 0, 0,
       0, 1, 2, 2, 2, 3, 0, 0, 0, 2, 0, 3, 1, 2, 2, 0, 0, 0, 3, 1, 2, 3,
       0, 2, 2, 2, 1, 0, 1, 2, 0, 3, 0, 3, 1, 3, 1, 3, 3, 2, 1, 1, 2, 1,
       3, 2, 0, 0, 2, 1, 1, 2, 2, 1, 3, 3, 0, 0, 3, 3, 3, 2, 2, 2, 3, 0,
       1, 0, 1, 3, 2, 3, 3, 1, 0, 3, 1, 2, 1, 3, 2, 2, 3, 2, 1, 3, 3, 3,
       2, 1, 0, 3, 1, 0, 2, 1, 1, 0, 0, 2, 2, 3, 1, 0, 2, 3, 3, 2, 2, 0,
       2, 2, 2, 3, 0, 1, 0, 3, 3, 1, 1, 1, 1, 1, 3, 0, 1, 0, 2, 3, 1, 1,
       3, 1, 2, 2, 3, 2, 1, 1, 2, 1, 0, 0, 0, 1, 1, 1, 3, 2, 3, 2, 0, 1,
       3, 0, 2, 3, 0, 0, 1, 2, 1, 3, 3, 3, 1, 2, 3, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 3, 3, 2, 2, 2, 3, 2, 0, 1, 2, 2, 1, 1, 2, 2, 3, 0, 2, 3, 2,
       1, 3, 0, 1, 2, 3, 0, 3, 3, 0, 2, 1, 1, 3, 0, 3, 2, 3, 0, 3, 1, 3,
       2, 0, 2, 2, 1, 1, 3, 2, 1, 0, 0, 1, 3, 2, 2, 2, 0, 0, 3, 2, 0, 2,
       0, 0, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1, 2, 1, 1, 0, 2, 0,
       3, 3, 0, 2, 0, 3, 1, 1, 3, 2, 0, 1, 3, 2, 3, 1, 2, 2, 3, 0, 3, 3,
       1, 2, 0, 1, 2, 3, 1, 3, 1, 0, 3, 0, 1, 2, 3, 0, 2, 3, 0, 1, 1, 0,
       2, 1, 1, 0, 2, 2, 2, 0, 1, 1, 0, 1, 2, 3, 3, 3, 0, 1, 3, 0, 2, 0,
       3, 3, 2, 0, 2, 1, 1, 1, 2, 1, 0, 1, 3, 3, 2, 1, 2, 3, 0, 1])

In [ ]:
df.drop("Outcome", axis= 1, inplace=True)

df["Outcome"] = label

df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,3
1,1,85,66,29,0,26.6,0.351,31,1
2,8,183,64,0,0,23.3,0.672,32,2
3,1,89,66,23,94,28.1,0.167,21,1
4,0,137,40,35,168,43.1,2.288,33,3
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,1
764,2,122,70,27,0,36.8,0.340,27,2
765,5,121,72,23,112,26.2,0.245,30,3
766,1,126,60,0,0,30.1,0.349,47,0
767,1,93,70,31,0,30.4,0.315,23,1

In [ ]:
from sklearn import preprocessing

df_scaled = preprocessing.scale(df)

df_scaled=pandas.DataFrame(df_scaled,columns=df.columns)

df_scaled['Outcome']=df['Outcome']
df=df_scaled

In [ ]:
old_cols=df.columns.values
new_cols=['Insulin','Age','BMI','Glucose']
df=df.reindex(columns=new_cols)
df

      Insulin       Age       BMI   Glucose
0   -0.692891  1.425995  0.204013  0.848324
1   -0.692891 -0.190672 -0.684422 -1.123396
2   -0.692891 -0.105584 -1.103255  1.943724
3    0.123302 -1.041549 -0.494043 -0.998208
4    0.765836 -0.020496  1.409746  0.504055
..        ...       ...       ...       ...
763  0.870031  2.532136  0.115169 -0.622642
764 -0.692891 -0.531023  0.610154  0.034598
765  0.279594 -0.275760 -0.735190  0.003301
766 -0.692891  1.170732 -0.240205  0.159787
767 -0.692891 -0.871374 -0.202129 -0.873019

[768 rows x 4 columns]

In [ ]:
print(df.rename(columns={'Insulin':'Sugar','BMI':'Fat'}))

        Sugar       Age       Fat   Glucose
0   -0.692891  1.425995  0.204013  0.848324
1   -0.692891 -0.190672 -0.684422 -1.123396
2   -0.692891 -0.105584 -1.103255  1.943724
3    0.123302 -1.041549 -0.494043 -0.998208
4    0.765836 -0.020496  1.409746  0.504055
..        ...       ...       ...       ...
763  0.870031  2.532136  0.115169 -0.622642
764 -0.692891 -0.531023  0.610154  0.034598
765  0.279594 -0.275760 -0.735190  0.003301
766 -0.692891  1.170732 -0.240205  0.159787
767 -0.692891 -0.871374 -0.202129 -0.873019

[768 rows x 4 columns]